name: Inference Pipeline

on:
  push:
    branches: [ inference ]
  pull_request:
    branches: [ inference ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        cd ${{ github.workspace }}
        python -m pytest tests/ -v

  train:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run training
      run: |
        cd ${{ github.workspace }}
        python src/train.py
        
    - name: Upload model artifact
      uses: actions/upload-artifact@v3
      with:
        name: model-train
        path: model_train.pkl
        retention-days: 30

  inference:
    runs-on: ubuntu-latest
    needs: train
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Download model artifact
      uses: actions/download-artifact@v3
      with:
        name: model-train
        path: .
        
    - name: Run inference
      run: |
        cd ${{ github.workspace }}
        python src/inference.py 